version: '3.8'

services:
  web:
    build: ./services/web
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./services/web/:/usr/src/app/
    ports:
      - 9999:5000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  postgres:
    build: services/postgres
    volumes:
      - ./:/tmp/db
      - $HOME/bigdata/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
      - PGUSER=postgres
    ports:
      - 9999:5432

volumes:
  postgres:


