name: tests
on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup python
    - name: docker
      run: |
        docker-compose up -d --build
        docker ps -a
        sleep 20
        ./load_tweets_sequential.sh
        docker-compose exec -T pg_normalized ./run_tests.sh
